# Generated by Django 2.0 on 2018-01-11 12:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('added', models.DateTimeField(default=datetime.datetime.now, verbose_name='added')),
                ('unseen', models.BooleanField(default=True, verbose_name='unseen')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('on_site', models.BooleanField(verbose_name='on site')),
            ],
            options={
                'verbose_name_plural': 'notices',
                'verbose_name': 'notice',
                'ordering': ['-added'],
            },
        ),
        migrations.CreateModel(
            name='NoticeQueueBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickled_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NoticeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('1', 'Email')], max_length=1, verbose_name='medium')),
                ('send', models.BooleanField(verbose_name='send')),
            ],
            options={
                'verbose_name_plural': 'notice settings',
                'verbose_name': 'notice setting',
            },
        ),
        migrations.CreateModel(
            name='NoticeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, verbose_name='label')),
                ('display', models.CharField(max_length=100, verbose_name='display')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('default', models.IntegerField(verbose_name='default')),
            ],
            options={
                'verbose_name_plural': 'notice types',
                'verbose_name': 'notice type',
            },
        ),
        migrations.CreateModel(
            name='ObservedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('added', models.DateTimeField(default=datetime.datetime.now, verbose_name='added')),
                ('signal', models.TextField(verbose_name='signal')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('notice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.NoticeType', verbose_name='notice type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'observed items',
                'verbose_name': 'observed item',
                'ordering': ['-added'],
            },
        ),
        migrations.AddField(
            model_name='noticesetting',
            name='notice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.NoticeType', verbose_name='notice type'),
        ),
        migrations.AddField(
            model_name='noticesetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.NoticeType', verbose_name='notice type'),
        ),
        migrations.AddField(
            model_name='notice',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_notices', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AddField(
            model_name='notice',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterUniqueTogether(
            name='noticesetting',
            unique_together={('user', 'notice_type', 'medium')},
        ),
    ]
