# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20161107_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[('1', 'Email')], max_length=1, verbose_name='medium'),
        ),
    ]
